### ISSUE TITLE
LibertyTunnel support?

### ISSUE THREAD

**Issue by mrbluecoat** [krlvm/Invader#1]
Can I use LibertyTunnel instead of PowerTunnel for Invader?

**Comment by krlvm** [comment]
Invader was an **expiremental research tool** based on PowerTunnel v1.8.4 (January 2020) for narrow use cases and LibertyTunnel is a lightweight PowerTunnel edition without GUI, user blocklist support and some other functionality - it is was intended to circumvent ISP/government blocks. If you just want to run Invader (why?) in headless mode, run it with `-console` flag: `java -jar Invader.jar -console`
